theme = "franson"
baseurl = "http://cheetahexhaust.co.za:9000/"
languageCode = "en-us"
title = "Franson Manufacturing"

[taxonomies]
	gallery ="galleries"

[menu]
	[[menu.main]]
	name = "Home"
    weight = -110
    identifier = "home"
    url = "/"
    
    [[menu.main]]
	name = "Gallery"
    weight = 110
    identifier = "gallery"
    url = "/gallery/"
